// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InfoDialog: typeof import('./../src/components/InfoDialog/index.vue')['default']
    MarsColorPicker: typeof import('./../src/components/marsUI/mars-color-picker/index.vue')['default']
    MarsInputNumber: typeof import('./../src/components/marsUI/mars-input-number/index.vue')['default']
    MarsSelect: typeof import('./../src/components/marsUI/mars-select/index.vue')['default']
    MarsSlider: typeof import('./../src/components/marsUI/mars-slider/index.vue')['default']
    MarsSwitch: typeof import('./../src/components/marsUI/mars-switch/index.vue')['default']
    MarsTextarea: typeof import('./../src/components/marsUI/mars-textarea/index.vue')['default']
    OverlayDialog: typeof import('./../src/components/OverlayDialog/index.vue')['default']
    PageForm: typeof import('./../src/components/PageForm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./../src/components/Tab/index.vue')['default']
    WebViewPage: typeof import('./../src/components/WebViewPage/index.vue')['default']
  }
}
